# Cross-platform build pipeline + NPM publish

name: $(Build.SourceVersion)
jobs:
- job: Linux
  displayName: "Linux - Ubuntu 18.04"
  pool:
    vmImage: 'Ubuntu 18.04'
  steps:
  - template: .ci/esy-build-steps.yml

- job: MacOS15
  displayName: "MacOS Catalina"
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - script: brew update
  - script: brew install libtool
  - template: .ci/esy-build-steps.yml

- job: MacOS14
  displayName: "MacOS High Sierra"
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: brew update
  - script: brew install libtool
  - template: .ci/esy-build-steps.yml

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: .ci/esy-build-steps.yml
